name: CI

on:
  push:
    branches:
      - main

jobs:
  my-testing:
    runs-on: ubuntu:22.04
    
    steps:
    - name: Print Hello Message
      run: echo "Hello world from Testing!"
  my-deployment:
    runs-on: ubuntu:22.04
    
    steps:
    - name: Print Hello Message
      run: echo "Hello world from Deployment!"
    
      
